# This is a basic workflow to help you get started with Actions
name: HTTP Status Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Pull Assessment Image
      run: docker pull mrksdh/assessment

    - name: Build and Test Container
      run: |
        docker-compose -f docker-compose.yml up --build -d
        docker run --rm mrksdh/assessment

    - name: Run Tests
      run: |
        echo Running tests...
